-- 7 PERGUNTA: LISTA PONTOS DE CADA JOGADOR PEL DATA DE PARTIDA E A PONTUAÇÃO FINAL DE SEU TIME USANDO ID DO JOGO COMPARTILHADO PELAS TABELAS

SELECT games.GAME_DATE_EST,games.PTS_home,teams_has_games.TEAM_ABBREVIATION,teams_has_games.PTS,teams_has_games.PLAYER_NAME
FROM games
INNER JOIN teams_has_games
ON games.GAME_ID = teams_has_games.GAME_ID
WHERE SEASON=2007;
