-- 5 PERGUNTA: MOSTRA MÉDIA DE PONTOS DOS TIMES NA TEMPORADA 2003 USANDO AS ID'S

USE nbadb;
-- Busca ID DO PRIMERIO JOGO DA TEMPORADA 2003
SELECT GAME_ID,SEASON FROM games WHERE SEASON=2003 ORDER BY GAME_ID ASC LIMIT 1; 

-- ID DO ULTIMO JOGO DA TEMPORADA 2003

SELECT GAME_ID,SEASON FROM games WHERE SEASON=2003 ORDER BY GAME_ID DESC LIMIT 1; 

-- MOSTRA MÉDIA DE PONTOS DOS TIMES NA TEMPORADA 2003 USANDO AS ID'S

SELECT AVG (PTS) AS Media_entre_primeiro_e_ultimo_jogo_da_temporada2003 FROM teams_has_games WHERE GAME_ID BETWEEN 10300001 AND 40300405; 